---
# handlers file for Nainterceptor.nginx-redirect
- name: "Restart nginx"
  service:
    name: nginx
    state: restarted
  when: ansible_distribution == 'CentOS'

- name: "Enable nginx"
  service:
    name: nginx
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS'